# general settings
name: Denoising_MTSNet_NB1_Sigma25_efficient_p0_fixed_no_mixing
model_type: ImageCleanModel
scale: 1
num_gpu: 2  # set num_gpu: 0 for cpu mode
manual_seed: 100

# dataset and data loader settings
datasets:
  train:
    name: TrainSet
    type: Dataset_GaussianDenoising
    sigma_type: constant
    sigma_range: 25
    in_ch: 3    ## RGB image
    dataroot_gt: /lustre/mehmet/LargeData/
    dataroot_lq: none
    geometric_augs: true

    filename_tmpl: '{}'
    io_backend:
      type: disk

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 4
    batch_size_per_gpu: 4

    ### -------------Progressive training--------------------------
    mini_batch_sizes: [4,2]             # Batch size per gpu   
    iters: [1000000,200000]
    gt_size: 384   # Max patch size for progressive training
    gt_sizes: [256,384]  # Patch sizes for progressive training.
    ### ------------------------------------------------------------

    ### ------- Training on single fixed-patch size 128x128---------
    # mini_batch_sizes: [8]   
    # iters: [300000]
    # gt_size: 128   
    # gt_sizes: [128]
    ### ------------------------------------------------------------

    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet
    type: Dataset_GaussianDenoising
    sigma_test: 25
    in_ch: 3  ## RGB image
    dataroot_gt: /lustre/mehmet/TensorSumPytorch/KAIR-master/testsets/Kodak24
    dataroot_lq: none
    io_backend:
      type: disk

# network structures
network_g:
  type: MTSNet
  L: 4
  N: 56
  T: 3
  embed_dim: 9
  embed_style: Hybrid
  NB: 1
  window_scales: [8, 16, 32, 64]
  ffn_expansion_factor: 2.2
  FFactivation: null
  alpha: 1
  beta: 1
  alpha_decay: !!float 1e-1
  beta_decay: !!float 1e-1
  groups: 4
  bias: False
  post_mts_function: MHG
  em_window_scales: [8, 16, 32, 64]
  num_heads: 4
  dwconv_usage: True
  drop_block_p: 0.


# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  total_iter: 1500000
  warmup_iter: -1 # no warm up
  use_grad_clip: true

  # Split 300k iterations into two cycles. 
  # 1st cycle: fixed 3e-4 LR for 92k iters. 
  # 2nd cycle: cosine annealing (3e-4 to 1e-6) for 208k iters.
  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [200000, 200000,200000, 200000,200000,200000 ]       
    restart_weights: [1, 0.5, 0.25, 0.125,0.0625,0.03125]
    eta_mins: [0.0005,0.00025,0.000125,0.0000625,0.000031,0.000016]   
  
  mixing_augs:
    mixup: false
    mixup_beta: 0
    use_identity: true

  optim_g:
    type: AdamW
    lr: !!float 1e-3
    weight_decay: 0.
    betas: [0.9, 0.999]
  
  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: sum

# validation settings
val:
  window_size: 8
  val_freq: !!float 4e3
  save_img: false
  rgb2bgr: true
  use_image: false
  max_minibatch: 8

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 4e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
