# general settings
name: tinymtsnet_deblurring_train
model_type: ImageCleanModel
scale: 1
num_gpu: 8  # set num_gpu: 0 for cpu mode
manual_seed: 100

# dataset and data loader settings
datasets:
  train:
    name: tinymtsnet_train
    type: PairedImageDataset
    dataroot_gt: ./datasets/GoPro/train/sharp_crops.lmdb
    dataroot_lq: ./datasets/GoPro/train/blur_crops.lmdb
    geometric_augs: true

    filename_tmpl: '{}'
    io_backend:
      type: lmdb
    
    # data loader
    num_worker_per_gpu: 4
    batch_size_per_gpu: 4
    ### ------- Training on single fixed-patch size 256x256---------
    mini_batch_sizes: [4]   
    iters: [600000]
    gt_size: 256   
    gt_sizes: [256]
    ### ------------------------------------------------------------
                  
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: GoPro
    type: PairedImageDataset
    dataroot_gt: ./datasets/GoPro/test/target.lmdb
    dataroot_lq: ./datasets/GoPro/test/input.lmdb
    io_backend:
      type: lmdb
   

# network structures
network_g:
  type: TinyTensorNet
  L: 3
  N: 48
  T: 3

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  total_iter: 600000
  warmup_iter: -1 # no warm up
  use_grad_clip: true

  scheduler:
    type: MultiStepLR
    milestones: [150000, 300000, 450000]
    gamma: 0.1  
  
  mixing_augs:
    mixup: false
    mixup_beta: 0.
    use_identity: true

  ema_decay: 0.9999
  optim_g:
    type: AdamW
    lr: !!float 1e-3
    weight_decay: 0.
    betas: [0.9, 0.999]
  
  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1
    reduction: sum

# validation settings
val:
  window_size: 8
  val_freq: !!float 4e4
  save_img: false
  rgb2bgr: true
  use_image: false
  max_minibatch: 4
  
  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 200
  save_checkpoint_freq: !!float 4e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500

